### ISSUE TITLE
Certain modded structures generate, while others do not.

### ISSUE THREAD

**Issue by Thombias** [CorgiTaco-Archive/overworld-two-forge#3]
Minecraft version: 1.16.5
Forge version: 36.1.0
Mod version: overworld_two-1.0-Forge-1.16.4.jar

On an Overworld Two world i have tested all spawnable structures from all the mods i have installed in my WIP modpack by using the /locate command and by flying through the world in spectator mode. Here's what i've found so far:

Ice and Fire: Gorgon Temples, Graveyards and Mausoleums do not generate at all.
Dragon Caves, Dragon Roosts, Cyclope Caves, Pixie Villages, Myrmex Colonies, Hydra Caves and Siren Islands do generate in their expected biomes. (These can't be located with the /locate command weirdly enough)

Atmospheric: The Arid Shrine doesn't generate.

Autumnity: The Maple Witch hut doesn't generate.

Dungeon Crawl: Not a single dungeon generated in my test world.

Quark: This is an odd one. All of its features do generate like normal, except for the Big Dungeons (Or varied dungeons, whatever these things are called.)

Stoneholm, Underground Villages (Forge): The underground villages do not generate.

And finally, here are some other mods that generate structures and i can confirm through my testing that these are working 100% properly: Dungeons Plus, When Dungeons Arise, YUNG's Better Mineshafts (It replaces default Mineshafts with its own seperate Mineshaft structure, so i was surprised it works out of the box.)

Hoping to see you address these incompatibilites when you find the time for it! ^.^
This is a great mod which helps a lot with generating new chunks in a heavily modded environment. My TPS are very stable now and generating chunks is way faster and smoother than before.

Also, in case you need the structure IDs to make them spawn in overworld Two worlds, i'm writing them all down here:
iceandfire:gorgon_temple | iceandfire:graveyard | iceandfire:mausoleum | atmospheric:arid_shrine | autumnity:maple_witch_hut | dungeoncrawl:dungeon | quark:big_dungeon | stoneholm:underground_village

**Comment by raffle2** [comment]
Have the same issue here too, a lot of structure mods are currently not compatible, wish I knew about this post beforehand since I also just tested everything through a lot of crashes but I'm glad I'm not the only one, here's hoping it's not too much of a drag to fix in the future since I would love to use this mod, it's a big difference in fps but I prioritize the content :(
